name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name:  Print greeting
        run: echo "Hello World - Welcome to Github actions!"
      - name: Print goodbye
        run: echo "Done with First Workflow -Bye!"
