name: First Workflow
on: workflow_dispatch
#on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name:  Print greeting
        run: echo "Hello World Arun - Welcome to Github actions!"
      - name: Print goodbye
        run: echo "Arun Tonio 123 New Done with First Workflow -Byeeeeeeee!"
